### ISSUE TITLE
[Docs] Include instructions for setting cluster name on Kubernetes installations of the Operator

### ISSUE THREAD

**Issue by eedugon** [elastic/opentelemetry#35]
We should add details in our main document (https://github.com/elastic/opentelemetry/tree/main/docs/kubernetes/operator/README.md) details about how to customize the `values.yaml` before installing the operator via helm, and explain use cases where this might be needed, like:

- Adding cluster name
(already added)- Integrate with cert-manager for automatic certificates generation and renew.

Then we have to provide specific details for the `clusterName` use case.

**Comment by eedugon** [comment]
@gizas : would you provide some details about how exactly the `k8s.cluster.name` is retrieved for cloud based clusters like GKE, AKS and EKS? Are all of them supported for that?

I'd like to get a better knowledge of what systems get that field automatically populated and in what other systems the users should manually set `clusterName` if they are planning to monitor multiple clusters.

thanks!

**Comment by gizas** [comment]
Heyy @eedugon , the k8s.cluster name retrieval is based on the [resourcedetectionprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/README.md). We configure 3 different instances of the same processor in https://github.com/elastic/opentelemetry/blob/main/resources/kubernetes/operator/helm/values.yaml#L63-L82, one per major cloud provider.

In case the auto detection does not work, user can also set the [clusterName` variable](https://github.com/elastic/opentelemetry/blob/main/resources/kubernetes/operator/helm/values.yaml#L44C1-L45C23)
