### ISSUE TITLE
[docs] Consider reorganizing the Kubernetes OTel+EDOT getting started guide

### ISSUE THREAD

**Issue by eedugon** [elastic/opentelemetry#36]
As the current Otel operator getting started doc (https://github.com/elastic/opentelemetry/tree/main/docs/kubernetes/operator) is growing (and we are planning to add sections), we need to evaluate the possibility of dividing it in multiple sub-docs, with the main doc as a reference and guide linking to the other docs.

Something like:

README.md: Entry point, with links to docs like (based in the current table of contents of the doc):
- components-description.md
- guided-installation.md
- manual-installation.md
- customizing-configuration.md
- instrumenting-applications.md
(Limitations and compatibility matrix could remain in the main README)

Another possibility to explore would be to keep the installation information in the main doc, and just move out of the doc the sections:
- components-description
- customizing-configuration

cc: @rogercoll , I will prepare a PR and preview and we can discuss different options.

Update: whatever change we implement it will be important to keep this URL available: https://github.com/elastic/opentelemetry/tree/8.16/docs/kubernetes/operator#cert-manager, as it's linked from Kibana Onboarding UX.

So, the main page should keep an anchor to `#cert-manager` related information, which makes sense anyway :)

**Comment by jackshirazi** [comment]
I think this is done?

**Comment by eedugon** [comment]
Hi @jackshirazi ! No, this isn't completed. It's going to be my next task. I'm going so suggest a change in the README.md doc (which is quite long) and probably move certain parts (like the components description) to a separate doc, or include it in an `expandable` section to facilitate reading.

Of course if afterwards you and the team don't like the proposed change we could cancel the PR and close this issue.
